### ISSUE TITLE
Exception dumping empty mapping

### ISSUE THREAD

**Issue by jepler** [elpekenin/circuitpython_toml#3]
```py
>>> toml.dumps({'y': {}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jepler/src/community-bundle/libraries/helpers/toml/toml/_toml.py", line 392, in dumps
    del table, _order
UnboundLocalError: local variable 'table' referenced before assignment
```
I think this occurs because the inner loop never executes and so `table` has never been assigned.

**Comment by elpekenin** [comment]
Fixed on https://github.com/elpekenin/circuitpython_toml/commit/62792ce1cb59456c78747ed37108c18cab1ec0b8, thanks.

Added a new tag (0.1.4) for it, so `circup` shouldnt take long to catch the update :D

**Comment by jepler** [comment]
Thank you
