### ISSUE TITLE
Tables stop after a new line

### ISSUE THREAD

**Issue by dtcooper** [elpekenin/circuitpython_toml#6]
Given the following toml with a newline between table items,

```toml
[test]
one = true

two = true
```

Represented as a dict we get,

```python
# two not inserted in test dict
{'test': {'one': True}, 'two': True}
```
rather than the item `two` being included in the table which is what we would expect,

```python
# this is what we would expect, two properly inserted into the test dict
{'test': {'one': True, 'two': True}}
```

Thanks for the great library!

**Comment by elpekenin** [comment]
I recall thinking about it and assumng "it has to reset on empty lines to access the root table again"

Turns out, if only i had RTFM, it does not reset at all. Fix on its way as i was actually thinking about refactoring the test suite during the weekend.

**Comment by dtcooper** [comment]
Well, it is an odd quirk that once you create a `[table]` you can no longer access the global namespace/root table. So don't be too hard on yourself! 😝

**Comment by elpekenin** [comment]
Fixed now, soon on circup as i will create a new tag/release :D

Thx for the report

**Comment by dtcooper** [comment]
Thanks!
